### ISSUE TITLE
Goto, Fill and Submit issues where Fill is almost working everytime

### ISSUE THREAD

**Issue by 2Belette** [nwallace/passff#103]
Hi, 
First would like to say THANKS YOU for this plugin! I am coming from 1password on Mac and moving to Linux I couldn't find any better alternative!

I got 50 sites stored in pass, and around half of them are not working automaticaly.
I firs checked the Preferences/Autofilling/input names and added the missing one (using page inspector to see the name of the forms)
Everything is working when I use "Fill", almost everytime when I use 'Fill and Submit" but half of my website are not working on "Goto, Fill and Submit".
Sometimes it doesn't fill anything, sometimes I get an error like it is too quick to fill the forms before the page is loaded.

Any idea?

many thanks
belette

Edit : I made lot of tests and I realized that most of the issues are solved with the 'Try to auto fill page login forms' option checked. (only 5 remaining sites are not working)
The only problem si that PassFF tries to fill almost every pages even if the page is not in PassFF! and puts 'undefined' on a lot of forms..

The strange thing now is that for 2 sites nothing is done whatever option I try.
And more strange is for 3 sites I got the login form filled with the password and viceversa! I double checked Autofilling/input names & password are ok.
Perhaps only the last one can be solved, if you have any idea ...
Many thanks

**Comment by jvenant** [comment]
Hi,

I'm happy you like PassFF ^_^

How inputs are auto-filled can be tricky because there are lots of different approaches.
If the website use some javascript to generate the inputs or on events like onchange, it can have a huge impact on the capacity of passff to auto-fill.

for exemple, the  "Goto, Fill and Submit" try to find inputs in the html document dom once it is loaded.
if the login form is retreived through ajax and javascript after the document is loaded, passff might not be able to find it. Whereas when you use the manual feature, the login form is already present in the dom tree

I don't understand the difference of behavior between  "Goto, Fill and Submit" and 'Try to auto fill page login forms'. It should work exactly the same way...?

when the 'Try to auto fill page login forms' option is enable, PassFF will try to find a pass entry that match the current website. Currently, the algorithm used is far to be perfect and probably create many false positive. I didn't find any good alternative for now. You can find a description of the current algorithm here : #51

**Comment by tuxor1337** [comment]
Please reopen if this bug still applies to the most recent version from Github.
