### ISSUE TITLE
Bad search

### ISSUE THREAD

**Issue by Forever-Young** [nwallace/passff#172]
For example I have record named 'aws' in subdirectory, when I search for 'aws' it doesn't find it, but finds 'qiwiVisaCard' for some reason

**Comment by Midek** [comment]
I have noticed similar issue before, afraid i cant remember exact details right now.

I did notice other thing though, when i use different password for sub sites on same domain it always defaults to the first one, ex:
for mysite.com/owncloud as well as mysite.com/ampache. i have pass dir for mysite.com and .gpg files for owncloud and ampache in there. Passff will always default to ampache, even when im on owncloud page.

Would be cool if you could add option for more strict matching instead of fuzzy algorithm that is in place now.

**Comment by nwallace** [comment]
I too have seen derpy search results. I've been focusing on stability and bug fixes this past month, but I should have a big release ready by Christmas (woo!) and I'll try to slate in some time for this after that.

We definitely could add an option to use strict matching instead, but it should be possible to just improve the search algorithm to rank the results better. Any help on researching these types of algorithms would be appreciated :)

**Comment by nwallace** [comment]
I'm also going to close this, since it's the same as https://github.com/nwallace/passff/issues/127

Please move this conversation over to that thread
