### ISSUE TITLE
Configuration is lost from time to time

### ISSUE THREAD

**Issue by varac** [nwallace/passff#184]
Once in a while, I need to re-add all custom changes i made to the "Login input names", because they get reset to the defaults for unknown reason.
This is annoying. Is this a known bug ?

**Comment by FlorianFranzen** [comment]
I have the same problem. Every time I reopen Firefox, all the settings are gone.

**Comment by tuxor1337** [comment]
This will probably be fixed with WebExtensions...

**Comment by FlorianFranzen** [comment]
@tuxor1337 I do have the impression this plugin will not officially switch to its WebExtension implementation until it is absolutely necessary, which means we will have to wait till August/November for a fix.

Alternatively one can of course install Firefox Developer Edition, package and install an unsigned xpi by hand with your fork, and then copy two extra files based on a description in a random GitHub issue to get it to work, which I would hardly call an ideal solution either. 

I know a lot of extensions that retain their settings over multiple sessions, so what is the problem here?

**Comment by tuxor1337** [comment]
Don't lose hope my friend. The master branch of this extension has already switched to WebExtensions and all the information for a manual install are in the official README and INSTALLATION files. However, there is still some work in progress, e.g. regarding the `install_host_app.sh`.

We simply don't have the manpower to support two versions of this extension in parallel. Now we are focussing on WebExtensions.

**Comment by tuxor1337** [comment]
Closing this, since it doesn't apply to current master.
