### ISSUE TITLE
Security of passff

### ISSUE THREAD

**Issue by Epholys** [nwallace/passff#190]
Hello dear `pasff` developers,

In the light of [Lastpass' browser extension vulnerability](https://blog.lastpass.com/2017/03/security-update-for-the-lastpass-extension.html/), I am curious about passff security. I know Lastpass have certainly a bigger attack surface and that you can't assure passff is completely secure, but I would love to hear what you think about the security of your work!

I am sorry if this question is misplaced or obvious, I am not well-versed in web security.

Keep up being awesome!

**Comment by tuxor1337** [comment]
Actually, I wouldn't expect too much. PassFF doesn't have enough manpower and, since the implementation of passff is conceptually similar to the implementation of Lastpass (content script injection and execution of external scripts on the host machine), I expect that (at least) the same vulnerabilities apply. But (as with the exploit you linked to) this is very much depending on security of the implementations of Firefox features such as host apps and content scripts.

In the end, you are executing stuff in a browser - and modern browsers are really hopeless constructions as far as security is concerned. Nobody can really guarantee decent safety with all those ever changing web standard etc. etc.

I'm closing this since an issue tracker is not the right place to discuss this.

**Comment by Epholys** [comment]
Thanks a lot for your comment, it cleared some doubts I had. Keep rockin'!
