### ISSUE TITLE
Utilize input context menu

### ISSUE THREAD

**Issue by jonhoo** [nwallace/passff#20]
It would be really convenient if passff could add an "Insert login"/"Insert password" item in the right-click menu for form elements that are identified as login inputs.

**Comment by herriett** [comment]
Anything new? I was just looking for the same functionality as suggested here and could not find it (using version 1.7.3). The + button kind of works, but is less handy as it does not recognize the context nor fill out the registration password field.

**Comment by tuxor1337** [comment]
I don't understand your question. This issue has been closed as resolved. The OP was asking for an entry in the right-click context menu for filling in form fields. This feature has been implemented since April 2017. You seem to ask for something different. I suggest you to open a new issue for that.
